DIRS is not an attribute but a key
change .DIRS to a key since this failed as below:
TEMPLATES[0].DIRS.insert(0, SITE_TEMPLATES)
AttributeError: 'dict' object has no attribute 'DIRS'